prog:jumpfct.o menu.o main.o background.o perfect_collide.o animation.o chrono.o
	gcc jumpfct.o menu.o main.o background.o perfect_collide.o animation.o chrono.o -o prog -g  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf 
background.o:background.c
	gcc -c background.c -g
main.o:main.c
	gcc -c main.c -g
perfect_collide.o:perfect_collide.c
	gcc -c perfect_collide.c -g
menu.o:menu.c
	gcc -c menu.c -g
animation.o:animation.c
	gcc -c animation.c -g
chrono.o:chrono.c
	gcc -c chrono.c -g
jumpfct.o:jumpfct.c
	gcc -c jumpfct.c -g
